[package]
name = "d21"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
itertools.workspace = true
aocutil.workspace = true
indoc.workspace = true
yansi.workspace = true
memmap2 = "0.9.5"
